---
# Install Redmon dependencies
- name: "Install Redmon dependencies"
  apt: pkg=${item} state=installed update-cache=yes
  with_items: ${redmon.dependencies}
  when_boolean: ${with_redmon}
  tags:
    - redmon

# Install Redmon gems
- include: tasks/gems.yml
  with_items: ${redmon.gems}

# Install Redmon init script
- name: "Install Redmon init script"
  template: src=templates/redmon.j2 dest=/etc/init.d/${redmon.service} owner=root group=root mode=0755
  when_boolean: ${with_redmon}
  tags:
    - redmon

# Ensure Redmon is running
- name: "Ensure Redis server is running"
  service: name=${redmon.service} state=started
  when_boolean: ${with_redmon}
  tags:
    - redmon